#!/bin/bash

#include ip of servers
. /root/hosts_geo

#remove old files
rm -rf Geocit134

# Clone git repository
git clone https://github.com/idanylyuk/Geocit134.git
cd Geocit134

db_name='******'
db_user='********'
db_password='********'
gmail_user='**********'
gmail_password='**************'
#fix pom.xml file bugs
find . -type f -name "pom.xml" -exec sed -i 's/http:\/\/repo.spring.io/https:\/\/repo.spring.io/g' {} +
find . -type f -name "pom.xml" -exec sed -i 's/<distributionManagement>/<!--<distributionManagement>/g' {} +
find . -type f -name "pom.xml" -exec sed -i 's/<\/distributionManagement>/<\/distributionManagement>-->/g' {} +

#fix database application connection
find . -type f -name "application.properties" -exec sed -i "s/http:\/\/localhost/http:\/\/$server_ip/g" {} +
find . -type f -name "application.properties" -exec sed -i "s/postgresql:\/\/localhost:5432\/ss_demo_1/postgresql:\/\/$db_server_ip:5432\/$db_name/g" {} +
find . -type f -name "application.properties" -exec sed -i "s/postgresql:\/\/35.204.28.238:5432\/ss_demo_1/postgresql:\/\/$db_server_ip:5432\/$db_name/g" {} +
find . -type f -name "application.properties" -exec sed -i "s/username=postgres/username=$db_user/g" {} +
find . -type f -name "application.properties" -exec sed -i "s/password=postgres/password=$db_password/g" {} +

# fix js localhost bugs
find . -type f -name "*.js" -exec sed -i "s/localhost:8080/$server_ip:8080/g" {} +

# fix e-mail data
find . -type f -name "application.properties" -exec sed -i "s/ssgeocitizen/$gmail_user/g" {} +
find . -type f -name "application.properties" -exec sed -i "s/password=softserve/password=$gmail_password/g" {} +

#fix favicon
find . -type f -name "index.html" -exec sed -i "s/\/src\/assets/\.\/static/g" {} +

#build project
mvn install

#deploy project
sudo mv target/citizen.war /opt/tomcat/webapps
